#!/usr/bin/env python3
"""ltxq v1.4 — submit/poll/collect draw-things-cli generations over SSH.
One-shot runner (default) and serve (warm worker) backends. Mac/Linux hosts.
Deps: python3 + pyyaml + system ssh/rsync/tar.
"""
import argparse, gc, hashlib, importlib.metadata, json, os, random, re, shlex, shutil, sqlite3, subprocess, sys, time, uuid
from pathlib import Path
import yaml

HERE = Path(__file__).resolve().parent
DB_PATH, CONF_PATH = HERE / "ltxq.db", HERE / "hosts.yaml"
SSH_OPTS = ["-o", "BatchMode=yes", "-o", "ConnectTimeout=10", "-o", "ServerAliveInterval=15"]
MUX_DIR = HERE / ".ssh_mux"; MUX_DIR.mkdir(exist_ok=True)
MUX_OPTS = ["-o", "ControlMaster=auto",
            "-o", "ControlPath=" + str(MUX_DIR / "cm-%r@%h-%p"),
            "-o", "ControlPersist=10m"]

PCT   = re.compile(r"(\d{1,3})\s*%")
WROTE = re.compile(r"^Wrote:\s*(\S+)", re.M)
TOTAL = re.compile(r"Total generation time[^:]*:\s*([\d.]+)")
STEPS = re.compile(r"\((\d+) step\(s\)\): avg ([\d.]+) s, median ([\d.]+) s")
EVT   = re.compile(r"DT_WORKER_EVENT\s*(\{.*\})")
GENP  = re.compile(r"Generated\s*\[[^\]]*\]\s*(\d{1,3})\s*%")
MDIR_HDR = re.compile(r"^Models directory:\s*(.+)$", re.M)
ROW = re.compile(r"^(\S+\.ckpt)\s{2,}(.+?)\s{2,}(official|community)\s+(yes|no)(?:\s+(\S+))?\s*$", re.M)
SHUTDOWN = shlex.quote('{"command":"shutdown"}')

FLAGMAP = (("image", "--image"), ("audio", "--audio"), ("first_frame", "--first-frame"),
           ("middle_frame", "--middle-frame"), ("last_frame", "--last-frame"),
           ("input_video", "--input-video"))
PATH_FLAGS = ("--config-file", "--prompt-file", "--output", "--image", "--audio",
              "--first-frame", "--middle-frame", "--last-frame", "--input-video",
              "--models-dir")

PROBE_SH = '''
echo "HOME=$HOME"; echo "UNAME=$(uname -s)"
test -x {cli} && echo "CLI=ok" || echo "CLI=missing"
echo "EV=$DRAWTHINGS_MODELS_DIR"
cand() {{
  [ -d "$1" ] || return 0
  k=$(ls -1 "$1"/*.ckpt 2>/dev/null | wc -l | tr -d " ")
  echo "CAND|$2|$1|$k"
}}
[ -n "$DRAWTHINGS_MODELS_DIR" ] && cand "$DRAWTHINGS_MODELS_DIR" env
P="$HOME/Library/Containers/com.liuliu.draw-things/Data/Library/Preferences/com.liuliu.draw-things.plist"
if [ -f "$P" ]; then
  plutil -convert json -o - "$P" 2>/dev/null \\
    | grep -oiE '"/(volumes|users)/[^"]+"' | tr -d '"' | sort -u | head -10 \\
    | while IFS= read -r s; do
        [ -d "$s" ] || continue
        k=$(ls -1 "$s"/*.ckpt 2>/dev/null | wc -l | tr -d " ")
        echo "CAND|prefext|$s|$k"
      done
fi
cand "$HOME/Library/Containers/com.liuliu.draw-things/Data/Documents/Models" container
cand "$HOME/Documents/Models" documents
cand "$(CDPATH= cd -- "$(dirname -- {cli})" 2>/dev/null && pwd)/Models" bindir
'''
ORDER = ("env", "prefext", "container", "documents", "bindir")

SCHEMA = """
CREATE TABLE IF NOT EXISTS jobs(
  id TEXT PRIMARY KEY, created_at INT, name TEXT, parent_id TEXT,
  host TEXT, model TEXT, prompt TEXT, config_text TEXT,
  status TEXT, remote_dir TEXT, remote_wrote TEXT, local_dir TEXT, local_out TEXT,
  pct INT DEFAULT 0, pct_ts INT, started_at INT, finished_at INT, exit_code INT,
  total_gen_s REAL, steps INT, step_avg_s REAL, step_median_s REAL,
  assets TEXT, extra_args TEXT, num_frames INT, fps REAL, ext TEXT,
  backend TEXT, cur_off INT, log_tail TEXT, note TEXT, chain TEXT, batch TEXT);
CREATE TABLE IF NOT EXISTS hosts(
  alias TEXT PRIMARY KEY, max_jobs INT DEFAULT 1, enabled INT DEFAULT 1,
  home TEXT, models_dir TEXT, uname TEXT, backend TEXT,
  dest TEXT, ssh_opts TEXT, mux INT DEFAULT 1);
CREATE TABLE IF NOT EXISTS registry(
  host TEXT, model TEXT, name TEXT, source TEXT, downloaded INT, hf TEXT, seen_at INT,
  PRIMARY KEY(host, model));
"""
MIGRATIONS = ("ALTER TABLE jobs ADD COLUMN assets TEXT",
              "ALTER TABLE jobs ADD COLUMN extra_args TEXT",
              "ALTER TABLE jobs ADD COLUMN num_frames INT",
              "ALTER TABLE jobs ADD COLUMN ext TEXT",
              "ALTER TABLE jobs ADD COLUMN backend TEXT",
              "ALTER TABLE jobs ADD COLUMN cur_off INT",
              "ALTER TABLE jobs ADD COLUMN fps REAL",
              "ALTER TABLE hosts ADD COLUMN models_dir TEXT",
              "ALTER TABLE hosts ADD COLUMN uname TEXT",
              "ALTER TABLE hosts ADD COLUMN backend TEXT",
              "ALTER TABLE hosts ADD COLUMN dest TEXT",
              "ALTER TABLE hosts ADD COLUMN ssh_opts TEXT",
              "ALTER TABLE hosts ADD COLUMN conn_type TEXT DEFAULT 'ssh'",
              "ALTER TABLE hosts ADD COLUMN cli_path TEXT",
              "ALTER TABLE hosts ADD COLUMN mux INT DEFAULT 1",
              "ALTER TABLE jobs ADD COLUMN chain TEXT",
              "ALTER TABLE jobs ADD COLUMN batch TEXT")

RUNNER = """#!/bin/sh
# generated by ltxq v1.4
cd "$(dirname "$0")" || exit 97
USE_PTY={pty}
echo $$ > pid
date +%s > started_at
run_cli() {{
  if [ "$USE_PTY" = "1" ]; then
    case "$(uname -s)" in
      Darwin) script -q /dev/null {cli} generate {args} ;;
      *)      script -qec "{cli} generate {args}" /dev/null ;;
    esac
  else
    {cli} generate {args}
  fi
}}
run_cli > log.txt 2>&1 &
echo $! > cli_pid
wait $!
echo $? > exit_code
date +%s > finished_at
"""

POLL_CMD = ('cd {rd} 2>/dev/null || {{ echo NODIR; exit 0; }}; echo ---E; '
            'cat exit_code 2>/dev/null; echo ---P; cat cli_pid 2>/dev/null; echo ---L; '
            'tail -c 4000 log.txt 2>/dev/null; echo ---A; '
            'kill -0 "$(cat cli_pid 2>/dev/null)" 2>/dev/null && echo alive || echo dead')

HOSTDEST = {}                                   # alias -> (dest, extra_opts, mux)

def conf():
    c = yaml.safe_load(CONF_PATH.read_text())
    for k, v in dict(cli_path="~/tod-dt-cli", poll_secs=10, stall_secs=900,
                     remote_root="genwork", movies_dir="~/Movies/generations",
                     use_pty=True, keep_remote=False, download_missing=False,
                     disable_preview=True, offline=False, hosts=[]).items():
        c.setdefault(k, v)
    return c

_DB_INITED = False

def db():
    """New sqlite connection. In threads an unclosed connection keeps its fds
    until a GC pass, so every caller in a long-lived process must close() it."""
    global _DB_INITED
    con = sqlite3.connect(DB_PATH, timeout=5)
    con.row_factory = sqlite3.Row
    con.execute("PRAGMA journal_mode=WAL")
    con.execute("PRAGMA busy_timeout=5000")
    if not _DB_INITED:                    # schema + migrations once per process
        con.executescript(SCHEMA)
        for ddl in MIGRATIONS:
            try: con.execute(ddl)
            except sqlite3.OperationalError: pass
        con.commit()
        _DB_INITED = True
    return con

def sync_hosts(con):
    hosts_cfg = conf()["hosts"]
    active_aliases = []
    for h in hosts_cfg:
        alias = h["alias"]
        active_aliases.append(alias)
        enabled = 0 if h.get("enabled") is False else 1
        con.execute("INSERT OR IGNORE INTO hosts(alias) VALUES(?)", (alias,))
        con.execute("UPDATE hosts SET max_jobs=?, models_dir=COALESCE(?, models_dir), "
                    "dest=?, ssh_opts=?, mux=?, conn_type=?, cli_path=?, enabled=? WHERE alias=?",
                    (h.get("max_jobs", 1), h.get("models_dir"),
                     h.get("dest") or alias, json.dumps(h.get("ssh_opts", [])),
                     0 if h.get("mux") is False else 1,
                     h.get("conn_type", "ssh"), h.get("cli_path"),
                     enabled, alias))
    if active_aliases:
        placeholders = ",".join("?" * len(active_aliases))
        con.execute(f"UPDATE hosts SET enabled=0 WHERE alias NOT IN ({placeholders})", active_aliases)
    con.commit(); load_dests(con)

def clean_tmp(max_age_s=86400):
    """Prune temporary files and staged keyframe extracts older than max_age_s."""
    tmp = HERE / "jobs" / "_tmp"
    if not tmp.is_dir():
        return
    now = time.time()
    for p in tmp.iterdir():
        if p.is_file():
            try:
                if now - p.stat().st_mtime > max_age_s:
                    p.unlink(missing_ok=True)
            except OSError:
                pass

def rotate_worker_logs(c, con, max_bytes=10 * 1024 * 1024):
    """Rotate remote worker.log on enabled hosts if size exceeds max_bytes and host is idle."""
    for h in con.execute("SELECT * FROM hosts WHERE enabled=1").fetchall():
        if not h["home"]:
            continue
        busy = con.execute("SELECT COUNT(*) FROM jobs WHERE host=? AND status IN "
                           "('uploading','running','collecting','suspect','cancelling')",
                           (h["alias"],)).fetchone()[0]
        if busy > 0:
            continue
        w = shlex.quote(wdir(h))
        cmd = (f"if [ -f {w}/worker.log ]; then "
               f"sz=$(wc -c < {w}/worker.log 2>/dev/null || echo 0); "
               f"if [ \"$sz\" -gt {max_bytes} ]; then "
               f"cp {w}/worker.log {w}/worker.log.prev 2>/dev/null && : > {w}/worker.log; "
               f"echo ROTATED; fi; fi")
        try:
            r = ssh(h["alias"], cmd, timeout=15)
            if "ROTATED" in r.stdout:
                print(f"{h['alias']}: rotated worker.log (> {max_bytes // (1024*1024)}MB)")
        except Exception:
            pass

def load_dests(con):
    HOSTDEST.clear()
    for r in con.execute("SELECT alias, dest, ssh_opts, mux, conn_type FROM hosts"):
        HOSTDEST[r["alias"]] = (r["dest"] or r["alias"],
                                json.loads(r["ssh_opts"] or "[]"), bool(r["mux"]),
                                r["conn_type"] or "ssh")

def dest_of(alias):
    d, extra, mux, _ = HOSTDEST.get(alias, (alias, [], True, "ssh"))
    return d, [os.path.expanduser(x) if x.startswith("~") else x for x in extra], mux

def ssh_eopts(alias):
    _, extra, mux = dest_of(alias)
    return list(SSH_OPTS) + (list(MUX_OPTS) if mux else []) + list(extra)

def is_local(alias):
    """conn_type from the in-memory host cache; falls back to a db lookup
    (closed immediately) only when the alias isn't cached yet."""
    if alias in HOSTDEST:
        return HOSTDEST[alias][3] == "local"
    con = db()
    try:
        r = con.execute("SELECT conn_type FROM hosts WHERE alias=?", (alias,)).fetchone()
        return bool(r) and (r["conn_type"] or "ssh") == "local"
    finally:
        con.close()


def run_cmd(alias, cmd, timeout=60):
    """Run a shell command on the host: locally via zsh, else over ssh.
    Both paths return CompletedProcess with the same shape."""
    if is_local(alias):
        return subprocess.run(["/bin/zsh", "-c", cmd],
                              capture_output=True, text=True, timeout=timeout)
    d, _, _ = dest_of(alias)
    return subprocess.run(["ssh", *ssh_eopts(alias), d, cmd],
                          capture_output=True, text=True, timeout=timeout)


def ssh(alias, cmd, timeout=60):
    return run_cmd(alias, cmd, timeout)

def set_job(con, jid, **kw):
    if kw:
        con.execute(f"UPDATE jobs SET {','.join(k + '=?' for k in kw)} WHERE id=?",
                    list(kw.values()) + [jid])
        con.commit()

def dollar_home(p):
    return "$HOME/" + p[2:] if p.startswith("~/") else p

def wdir(h):
    return f"{h['home']}/genwork/worker"

KFREF = re.compile(r"@([^@\s]+)@")

def resolve_extra(extra, rd=None):
    """Rewrite @file@ tokens referencing uploaded assets to their remote path:
    serve backend gets the absolute job-dir path, oneshot the bare name
    (runner.sh cds into the job dir)."""
    out = []
    for t in extra:
        out.append(KFREF.sub(lambda m: (f"{rd}/{m.group(1)}" if rd else m.group(1)), t))
    return out

def make_runner(model, cli_path, use_pty, assets, extra, c, ext, models_dir=None):
    args = (f"--model {shlex.quote(dollar_home(model))} "
            f"--config-file config.json --output out.{ext} --prompt-file prompt.txt")
    if models_dir:
        args += f" --models-dir {shlex.quote(dollar_home(models_dir))}"
    if not c.get("download_missing"): args += " --no-download-missing"
    if c.get("disable_preview"):      args += " --disable-preview"
    if c.get("offline"):              args += " --offline"
    for a_ in assets:
        if a_.get("flag"):
            args += f" {a_['flag']} {shlex.quote(a_['file'])}"
    args += " " + " ".join(shlex.quote(t) for t in resolve_extra(extra))
    return RUNNER.format(pty=1 if use_pty else 0, cli=dollar_home(cli_path), args=args)

def upload(alias, rd, local_dir, names):
    if is_local(alias):
        dest = Path(rd).expanduser()
        dest.mkdir(parents=True, exist_ok=True)
        errs = []
        for n in names:
            try: shutil.copyfile(Path(local_dir) / n, dest / n)
            except OSError as e: errs.append(str(e))
        class _R: returncode = 1 if errs else 0; stderr = "\n".join(errs)
        return _R(), not errs
    tar = subprocess.Popen(["tar", "-cf", "-", "-C", str(local_dir), *names],
                           stdout=subprocess.PIPE)
    d = dest_of(alias)[0]
    r = subprocess.run(["ssh", *ssh_eopts(alias), d, f"mkdir -p {rd} && tar -xf - -C {rd}"],
                       stdin=tar.stdout, capture_output=True, text=True)
    tar.stdout.close(); tar.wait()
    return r, (r.returncode == 0 and tar.returncode == 0)

def cli_of(c, h):
    """CLI binary for this host: per-host override beats the global default."""
    if h is not None and h["cli_path"]:
        return h["cli_path"]
    return c["cli_path"]

def probe(con, c, alias):
    hrow = con.execute("SELECT cli_path FROM hosts WHERE alias=?", (alias,)).fetchone()
    cli = (hrow and hrow["cli_path"]) or c["cli_path"]
    r = ssh(alias, PROBE_SH.format(cli=shlex.quote(dollar_home(cli))))
    if r.returncode != 0:
        print(f"{alias}: UNREACHABLE: {r.stderr.strip()[:200]}"); return
    home, ev, cands = "", "", []
    for line in r.stdout.splitlines():
        if line.startswith("HOME="):    home = line[5:]
        elif line.startswith("EV="):    ev = line[3:]
        elif line.startswith("CAND|"):
            f = line.split("|", 3)
            if len(f) == 4: cands.append({"label": f[1], "path": f[2], "ck": f[3]})
    darwin = 'UNAME=Darwin' in r.stdout
    ok = [x for x in cands if x["ck"].isdigit() and int(x["ck"]) > 0]
    pick = next((x for lbl in ORDER for x in ok if x["label"] == lbl), None) \
        or (cands[0] if cands else None)
    con.execute("UPDATE hosts SET home=?, uname=?, models_dir=COALESCE(models_dir, ?) "
                "WHERE alias=?",
                (home, "Darwin" if darwin else "other",
                 pick["path"] if pick else "", alias))
    con.commit()
    pinned = con.execute("SELECT models_dir FROM hosts WHERE alias=?", (alias,)).fetchone()[0]
    print(f"{alias}: pinned: {pinned or 'NOT FOUND — pin models_dir: in hosts.yaml'}")
    for x in sorted(cands, key=lambda x: ORDER.index(x["label"]) if x["label"] in ORDER else 9):
        mark = "  <-- pinned" if pick and x["path"] == pick["path"] else ""
        print(f"  [{x['label']}] {x['path']}  ({x['ck']} ckpt){mark}")
    m = [x for x in cands if x["label"] == "env"]
    if ev and not m:
        print(f"  note: env var set ({ev}) but invisible to non-interactive ssh "
              "(export in ~/.zshrc — move to ~/.zshenv; pin decides regardless)")
    elif m and m[0]["ck"] == "0":
        print(f"  WARN: $DRAWTHINGS_MODELS_DIR points at an empty dir: {ev}")
    if len(ok) > 1:
        print("  note: several candidates hold ckpts — pin wins; override in hosts.yaml if wrong")

def _worker_alive(h):
    r = ssh(h["alias"], f'kill -0 "$(cat {shlex.quote(wdir(h))}/worker.pid 2>/dev/null)" '
                        f'2>/dev/null && echo ALIVE || echo DEAD')
    return "ALIVE" in r.stdout

def dispatch(c, con):
    for h in con.execute("SELECT * FROM hosts WHERE enabled=1").fetchall():
        busy = con.execute("SELECT COUNT(*) FROM jobs WHERE host=? AND status IN "
                           "('uploading','running','collecting','suspect','cancelling')",
                           (h["alias"],)).fetchone()[0]
        if busy >= h["max_jobs"]:
            continue
        job = con.execute("SELECT * FROM jobs WHERE status='queued' AND "
                          "(host IS NULL OR host=?) ORDER BY created_at, rowid LIMIT 1",
                          (h["alias"],)).fetchone()
        if job:
            cur = con.execute("UPDATE jobs SET status='uploading', host=? "
                              "WHERE id=? AND status='queued'", (h["alias"], job["id"]))
            con.commit()
            if cur.rowcount:
                launch(c, con, h, job)

def launch(c, con, h, job):
    if not h["home"] or not h["models_dir"]:
        probe(con, c, h["alias"])
        h = con.execute("SELECT * FROM hosts WHERE alias=?", (h["alias"],)).fetchone()
        if not h["home"]:
            set_job(con, job["id"], status="queued",
                    note="host unreachable — probe failed"); return
    note = resolve_chain(con, job)
    if note:
        set_job(con, job["id"], note=note)
        job = con.execute("SELECT * FROM jobs WHERE id=?", (job["id"],)).fetchone()
    backend = job["backend"] or h["backend"] or "oneshot"
    if backend == "serve":
        return launch_serve(c, con, h, job)
    rd = f"{h['home']}/{c['remote_root']}/jobs/{job['id']}"
    (Path(job["local_dir"]) / "runner.sh").write_text(make_runner(
        job["model"], cli_of(c, h), c["use_pty"], json.loads(job["assets"] or "[]"),
        json.loads(job["extra_args"] or "[]"), c, job["ext"] or "mov",
        models_dir=h["models_dir"]))
    names = ["runner.sh", "prompt.txt"]
    names.append("config.json" if (Path(job["local_dir"]) / "config.json").exists()
                 else "config.txt")
    names += [x["file"] for x in json.loads(job["assets"] or "[]")]
    r, ok = upload(h["alias"], rd, Path(job["local_dir"]), names)
    if not ok:
        set_job(con, job["id"], status="queued",
                note="upload failed: " + r.stderr.strip()[:200]); return
    md = dollar_home(h["models_dir"]) if h["models_dir"] else ""
    mdchk = (f'test -d {shlex.quote(md)} || {{ echo NODMDIR; exit 3; }}; ') if md else ""
    r = ssh(h["alias"], f"{mdchk}cd {shlex.quote(rd)} && nohup sh runner.sh > launch.log 2>&1 & echo $!")
    if "NODMDIR" in r.stdout:
        set_job(con, job["id"], note=f"models dir missing on host (volume unmounted?) "
                                     f"— retrying: {h['models_dir']}"); return
    ok = r.returncode == 0 and r.stdout.strip().isdigit()
    set_job(con, job["id"], status="running" if ok else "queued", host=h["alias"],
            backend="oneshot", remote_dir=rd,
            note="" if ok else "launch failed: " + (r.stderr or r.stdout).strip()[:200])

def serve_args(job, h, c):
    rd = f"{h['home']}/{c['remote_root']}/jobs/{job['id']}"
    exp = lambda p: dollar_home(p).replace("$HOME", h["home"], 1) if p else p
    args = ["--model", exp(job["model"]),
            "--config-file", f"{rd}/config.json", "--prompt-file", f"{rd}/prompt.txt",
            "--output", f"{rd}/out.{job['ext'] or 'mov'}"]
    if h["models_dir"]: args += ["--models-dir", exp(h["models_dir"])]
    if not c.get("download_missing"): args.append("--no-download-missing")
    if c.get("disable_preview"):      args.append("--disable-preview")
    if c.get("offline"):              args.append("--offline")
    for x in json.loads(job["assets"] or "[]"):
        if x.get("flag"): args += [x["flag"], f"{rd}/{x['file']}"]
    for t in resolve_extra(json.loads(job["extra_args"] or "[]"), rd):
        args.append(h["home"] + t[1:] if t.startswith("~/") else t)
    bad = [args[i] for i in range(len(args) - 1)
           if args[i] in PATH_FLAGS and not args[i + 1].startswith("/")]
    return rd, (None if bad else args), \
           ("non-absolute path for " + ", ".join(bad) if bad else None)

def launch_serve(c, con, h, job):
    if not _worker_alive(h):
        set_job(con, job["id"], status="queued", note="serve worker not running — run: "
                                     "python3 ltxq.py serve-start " + h["alias"]); return
    rd, args, err = serve_args(job, h, c)
    if err:
        set_job(con, job["id"], status="failed", note="serve args: " + err); return
    w = wdir(h)
    r = ssh(h["alias"], f"wc -c < {shlex.quote(w)}/worker.log 2>/dev/null || echo 0")
    try: off = int(r.stdout.strip() or 0)
    except ValueError: off = 0
    req = json.dumps({"id": job["id"], "args": args}, separators=(",", ":"))
    (Path(job["local_dir"]) / f"{job['id']}.req").write_text(req + "\n")
    names = [f"{job['id']}.req", "prompt.txt",
             "config.json" if (Path(job["local_dir"]) / "config.json").exists()
             else "config.txt"]
    names += [x["file"] for x in json.loads(job["assets"] or "[]")]
    up, ok = upload(h["alias"], rd, Path(job["local_dir"]), names)
    if not ok:
        set_job(con, job["id"], status="queued",
                note="upload failed: " + up.stderr.strip()[:200]); return
    ssh(h["alias"], f"cat {shlex.quote(rd + '/' + job['id'] + '.req')} > {shlex.quote(w)}/fifo")
    set_job(con, job["id"], status="running", host=h["alias"], backend="serve",
            remote_dir=rd, started_at=int(time.time()), cur_off=off, note="")

def poll_job(c, con, job):
    h = con.execute("SELECT * FROM hosts WHERE alias=?", (job["host"],)).fetchone()
    r = ssh(h["alias"], POLL_CMD.format(rd=shlex.quote(job["remote_dir"])))
    if r.returncode != 0:
        set_job(con, job["id"], note="poll ssh error: " + r.stderr.strip()[:200]); return
    parts, cur = {}, None
    for line in r.stdout.splitlines():
        if len(line) == 4 and line.startswith("---") and line[3] in "EPLA":
            cur = line[3]; parts[cur] = []
        elif cur:
            parts[cur].append(line)
    if "NODIR" in r.stdout:
        set_job(con, job["id"], note="remote job dir missing"); return
    exit_s = "\n".join(parts.get("E", [])).strip()
    log    = "\n".join(parts.get("L", []))
    alive  = "\n".join(parts.get("A", [])).strip() == "alive"
    now, upd = int(time.time()), {}
    m = PCT.findall(log)
    if m and min(int(m[-1]), 100) != job["pct"]:
        upd.update(pct=min(int(m[-1]), 100), pct_ts=now)
    t, s = TOTAL.search(log), STEPS.search(log)
    if t: upd["total_gen_s"] = float(t.group(1))
    if s: upd.update(steps=int(s.group(1)), step_avg_s=float(s.group(2)),
                     step_median_s=float(s.group(3)))
    upd["log_tail"] = log[-4000:]
    if exit_s:
        code = int(exit_s.split()[-1])
        upd.update(exit_code=code, finished_at=now)
        if job["status"] == "cancelling":
            upd["status"] = "cancelled"; cleanup(c, h, job["remote_dir"])
        elif code == 0:
            wrote = WROTE.findall(log)
            if not wrote:
                wrote = WROTE.findall(ssh(h["alias"],
                    f"tail -c 200000 {shlex.quote(job['remote_dir'] + '/log.txt')}").stdout)
            if wrote:
                upd.update(status="collecting", remote_wrote=json.dumps(wrote), note="")
            else:
                upd.update(status="collecting", note="exit 0 but no Wrote: line found")
        else:
            upd.update(status="failed", note=f"exit {code}")
    elif not alive:
        upd.update(status="failed", note="process gone, no exit_code (crash / host reboot?)")
    elif now - (upd.get("pct_ts") or job["pct_ts"] or now) > c["stall_secs"] \
            and job["status"] != "suspect":
        upd["status"] = "suspect"
    set_job(con, job["id"], **upd)

def poll_serve_job(c, con, job):
    h = con.execute("SELECT * FROM hosts WHERE alias=?", (job["host"],)).fetchone()
    w = shlex.quote(wdir(h))
    r = run_cmd(h["alias"],
        f'echo SIZE=$(wc -c < {w}/worker.log 2>/dev/null || echo 0); '
        f'kill -0 "$(cat {w}/worker.pid 2>/dev/null)" 2>/dev/null '
        f'&& echo WALIVE || echo WDEAD; '
        f'tail -c +{(job["cur_off"] or 0) + 1} {w}/worker.log 2>/dev/null',
        timeout=60)
    if r.returncode != 0:
        set_job(con, job["id"], note="poll ssh error: "
                + r.stderr.strip()[:200]); return
    raw = r.stdout
    m = re.match(r"SIZE=(\d+)\r?\n(WALIVE|WDEAD)\r?\n", raw)
    if m: size, walive, data = int(m.group(1)), m.group(2) == "WALIVE", raw[m.end():]
    else: size, walive, data = (job["cur_off"] or 0), True, raw
    if not data.endswith("\n"):
        data = data[:data.rfind("\n") + 1]
    chunk = data
    now, upd = int(time.time()), {"cur_off": (job["cur_off"] or 0) + len(data.encode())}
    for pat in (GENP, PCT):
        mm = pat.findall(chunk)
        if mm and min(int(mm[-1]), 100) != job["pct"]:
            upd.update(pct=min(int(mm[-1]), 100), pct_ts=now); break
    t, s = TOTAL.search(chunk), STEPS.search(chunk)
    if t: upd["total_gen_s"] = float(t.group(1))
    if s: upd.update(steps=int(s.group(1)), step_avg_s=float(s.group(2)),
                     step_median_s=float(s.group(3)))
    if chunk.strip():
        upd["log_tail"] = ((job["log_tail"] or "") + chunk)[-4000:]
    term, msg, dur = None, "", None
    for line in chunk.splitlines():
        e = EVT.search(line)
        if not e: continue
        try: ev = json.loads(e.group(1))
        except json.JSONDecodeError: continue
        if ev.get("id") != job["id"]: continue
        if ev["event"] == "started":     upd.setdefault("started_at", now)
        elif ev["event"] == "completed": term, dur = "completed", ev.get("duration")
        elif ev["event"] == "failed":    term, msg = "failed", ev.get("message", "unknown")
    if dur and "total_gen_s" not in upd: upd["total_gen_s"] = round(dur, 2)
    if term == "completed":
        if job["status"] == "cancelling":
            upd.update(status="cancelled", finished_at=now)
            cleanup(c, h, wdir(h).replace("/worker", ""))  # no-op guard; real dir below
            cleanup(c, h, job["remote_dir"])
        else:
            wrote = WROTE.findall(chunk)
            if not wrote:
                wrote = WROTE.findall(ssh(h["alias"],
                    f"tail -c 200000 {shlex.quote(wdir(h) + '/worker.log')}").stdout)
            if wrote:
                upd.update(status="collecting", remote_wrote=json.dumps(wrote), note="")
            else:
                upd.update(status="collecting", note="completed but Wrote not found")
    elif term == "failed":
        note = msg[:200]
        if "ArgumentParser.ValidationError" in msg:
            note = (note + " [ValidationError: cause earlier in worker.log — usual: "
                    "missing --model, non-absolute path, unknown flag]")[:300]
        if job["status"] == "cancelling": upd["status"] = "cancelled"
        else: upd.update(status="failed", exit_code=1, finished_at=now, note=note)
    elif not walive and job["status"] != "cancelling":
        upd.update(status="failed", finished_at=now,
                   note="worker died mid-job (check worker.log tail)")
    set_job(con, job["id"], **upd)

def cleanup(c, h, rd):
    if rd and not c["keep_remote"]:
        ssh(h["alias"], f"rm -rf {shlex.quote(rd)}")

def sha256(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()

def collect(c, con, job):
    wrote = json.loads(job["remote_wrote"] or "[]")
    if not (job["host"] and wrote):
        set_job(con, job["id"], note="collect: missing host/wrote paths"); return
    h = con.execute("SELECT * FROM hosts WHERE alias=?", (job["host"],)).fetchone()
    dest = Path(c["movies_dir"]).expanduser() / f"{slug(job['name'])}-{job['id']}"
    dest.mkdir(parents=True, exist_ok=True)
    srcs = [f"{dest_of(job['host'])[0]}:{shlex.quote(w)}" for w in wrote]
    if is_local(job["host"]):
        import shutil as _sh
        errs = []
        for w in wrote:
            try: _sh.copyfile(Path(w).expanduser(), dest / Path(w).name)
            except OSError as e: errs.append(str(e))
        class _R: returncode = 1 if errs else 0; stderr = "\n".join(errs)
        r = _R()
    else:
        r = subprocess.run(["rsync", "-a", "--partial", "--timeout=120",
                            "-e", "ssh " + " ".join(ssh_eopts(job["host"])),
                            *srcs, str(dest) + "/"],
                           capture_output=True, text=True, timeout=7200)
    outs = []
    for w in wrote:
        p = dest / Path(w).name
        if p.exists():
            outs.append({"wrote": w, "local": str(p), "size": p.stat().st_size,
                         "sha256": sha256(p)})
    if r.returncode != 0 or len(outs) != len(wrote):
        set_job(con, job["id"], note="rsync retry: " + r.stderr.strip()[-200:]); return
    meta = dict(job); meta["outputs"] = outs
    if job["num_frames"] and job["fps"]:
        meta["duration_s"] = round(job["num_frames"] / job["fps"], 2)
    meta["collected_at"] = int(time.time())
    (dest / "metadata.json").write_text(json.dumps(meta, indent=2, default=str))
    set_job(con, job["id"], status="done", local_out=str(dest),
            finished_at=int(time.time()), note="")
    cleanup(c, h, job["remote_dir"])
    print(f"collected {job['id']} -> {dest} ({len(outs)} file(s))")

def slug(s):
    return re.sub(r"[^A-Za-z0-9._-]+", "_", s).strip("_")[:48] or "job"

def video_of(job):
    """First collected video file of a finished job, or None."""
    out = Path(job["local_out"] or "")
    if not out.is_dir():
        return None
    vids = sorted(out.glob("*.mov")) + sorted(out.glob("*.mp4"))
    return str(vids[0]) if vids else None

def extract_frame(v, frame, dst, timeout=120):
    """Extract one frame of video v to PNG dst. frame: int / 'first' / 'last'.
    Returns the extracted frame number; raises RuntimeError/ValueError."""
    fr = str(frame).strip()
    if fr == "first":
        n = 0
    elif fr == "last":
        pr = subprocess.run(["ffprobe", "-v", "error", "-select_streams", "v:0",
                             "-count_frames", "-show_entries",
                             "stream=nb_read_frames", "-of", "csv=p=0", v],
                            capture_output=True, text=True, timeout=timeout)
        try: n = max(0, int(pr.stdout.strip()) - 1)
        except ValueError:
            raise RuntimeError("ffprobe failed: " + pr.stderr[-150:])
    elif not fr.isdigit():
        raise ValueError("frame must be a number, 'first' or 'last'")
    else:
        n = int(fr)
    r = subprocess.run(["ffmpeg", "-y", "-v", "error", "-i", v,
                        "-vf", f"select=eq(n\\,{n})", "-frames:v", "1", str(dst)],
                       capture_output=True, text=True, timeout=timeout)
    if r.returncode != 0 or not dst.exists():
        raise RuntimeError("ffmpeg: " + (r.stderr[-200:] or "no output"))
    return n

def resolve_chain(con, job):
    """Chain continuation: if the job has `chain` set (target slot), extract the
    last frame of the most recent finished generation and attach it to that
    slot. Jobs carrying a `batch` label look for the previous finished job
    *within that batch* only; unbatched jobs keep the global scope. Returns a
    note (also when skipped/omitted), or None. Never fails the job: a missing
    source or an extract error just runs without the frame."""
    slot = job["chain"]
    if not slot:
        return None
    flag = dict(FLAGMAP).get(slot)
    if not flag:
        return "chain: unknown slot " + slot
    assets = json.loads(job["assets"] or "[]")
    if any(a.get("flag") == flag for a in assets):
        return None                     # manual attachment wins; also requeue re-run
    if job["batch"]:
        prev = con.execute(
            "SELECT * FROM jobs WHERE status='done' AND id!=? AND local_out IS NOT NULL "
            "AND batch=? ORDER BY finished_at DESC, created_at DESC LIMIT 1",
            (job["id"], job["batch"])).fetchone()
        nogen = (f"chain: no finished generation in batch '{job['batch']}' yet "
                 "— ran without start frame")
    else:
        prev = con.execute(
            "SELECT * FROM jobs WHERE status='done' AND id!=? AND local_out IS NOT NULL "
            "ORDER BY finished_at DESC, created_at DESC LIMIT 1", (job["id"],)).fetchone()
        nogen = "chain: no finished generation to continue from — ran without start frame"
    v = video_of(prev) if prev else None
    if not v:
        return nogen
    tmp = Path(job["local_dir"]) / f"chain_{prev['id']}.tmp.png"
    try:
        n = extract_frame(v, "last", tmp)
    except (RuntimeError, ValueError) as e:
        tmp.unlink(missing_ok=True)
        return f"chain: extract failed ({e}) — ran without start frame"
    dst = tmp.with_name(f"chain_{prev['id']}_f{n}.png")
    tmp.rename(dst)
    assets.append({"flag": flag, "file": dst.name, "local": str(dst)})
    set_job(con, job["id"], assets=json.dumps(assets))
    return f"chain: {slot} = last frame (f{n}) of {prev['id']}"

def cmd_add(a):
    c, con = conf(), db(); sync_hosts(con)
    try:
        return _cmd_add(c, con, a)
    finally:
        con.close()

def _cmd_add(c, con, a):
    if ".." in a.model or a.model.startswith("/"):
        sys.exit("invalid --model: must be a model id, not a path with '..' or '/'")
    jid = uuid.uuid4().hex[:10]
    prompt = Path(a.prompt_file).read_text()
    if a.config_file:
        cfg_text = Path(a.config_file).read_text()
    else:
        t = HERE / "templates" / f"{a.model}.json"
        if not t.exists():
            sys.exit(f"no --config-file and no template at {t}")
        cfg_text = t.read_text()
    dups = []
    def _pairs(pairs):
        ks = [k for k, _ in pairs]
        dups.extend(k for k in set(ks) if ks.count(k) > 1)
        return dict(pairs)
    try:
        obj = json.loads(cfg_text, object_pairs_hook=_pairs)
    except json.JSONDecodeError as e:
        sys.exit(f"config is not valid JSON: {e}")
    if dups:
        print("warn: duplicate keys in config (last value wins): "
              + ", ".join(sorted(set(dups))))
    if a.config_json:
        obj.update(json.loads(a.config_json)); cfg_text = json.dumps(obj, indent=2)
    for k in ("width", "height"):
        if obj.get(k) and obj[k] % 64:
            print(f"warn: {k}={obj[k]} is not a multiple of 64")
    cm = obj.get("model")
    if isinstance(cm, str) and cm and cm != a.model:
        reg = con.execute("SELECT model FROM registry WHERE name=?", (cm,)).fetchone()
        if reg and reg[0] != a.model:
            print(f"warn: config model '{cm}' = {reg[0]} but --model is {a.model} "
                  "— --model governs resolution")
        elif not reg:
            print(f"note: config carries model name '{cm}'; resolution uses --model {a.model}")
    loras = [l.get("file") for l in obj.get("loras", []) if l.get("file")]
    if loras:
        print("lora deps:", ", ".join(loras), "(run 'check <id>' after host assignment)")
    batch = re.sub(r"[^A-Za-z0-9._-]+", "_", (a.batch or "").strip())[:48] or None
    if batch and batch != a.batch.strip():
        print(f"batch label normalized: {batch}")
    name = a.name or " ".join(prompt.split())[:48] or jid
    d = HERE / "jobs" / jid; d.mkdir(parents=True)
    (d / "prompt.txt").write_text(prompt)
    (d / "config.json").write_text(cfg_text)
    assets = []
    for attr, flag in FLAGMAP:
        p = getattr(a, attr, None)
        if p:
            src = Path(p).expanduser()
            shutil.copyfile(src, d / src.name)
            assets.append({"flag": flag, "file": src.name, "local": str(src)})
    for p in a.upload or []:
        src = Path(p).expanduser()
        shutil.copyfile(src, d / src.name)
        assets.append({"flag": None, "file": src.name, "local": str(src)})
    extra = []
    for ea in a.extra_arg or []:
        extra += shlex.split(ea)
    host_cli = c["cli_path"]
    if a.host:
        hr = con.execute("SELECT cli_path FROM hosts WHERE alias=?",
                         (a.host,)).fetchone()
        if hr and hr["cli_path"]: host_cli = hr["cli_path"]
    seed = a.seed if a.seed is not None else \
        (random.randint(1, 2**31 - 1) if a.new_seed else None)
    if seed is not None:
        extra += ["--seed", str(seed)]; print("seed:", seed)
    (d / "runner.sh").write_text(make_runner(a.model, host_cli, c["use_pty"],
                                             assets, extra, c, a.ext))
    con.execute("INSERT INTO jobs(id,created_at,name,parent_id,host,model,prompt,"
                "config_text,status,local_dir,pct_ts,assets,extra_args,num_frames,"
                "fps,ext,backend,chain,batch) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                (jid, int(time.time()), name, a.parent, a.host, a.model, prompt,
                 cfg_text, "queued", str(d), int(time.time()), json.dumps(assets),
                 json.dumps(extra), obj.get("numFrames"), obj.get("fps"),
                 a.ext, a.backend, a.chain, batch))
    con.commit(); print(jid)

def cmd_regen(a):
    con = db(); sync_hosts(con)
    try:
        return _cmd_regen(con, a)
    finally:
        con.close()

def _cmd_regen(con, a):
    p = con.execute("SELECT * FROM jobs WHERE id=?", (a.id,)).fetchone()
    if not p: sys.exit("no such job")
    pd = Path(p["local_dir"])
    cfg = pd / "config.json"
    if not cfg.exists(): cfg = pd / "config.txt"
    extra = json.loads(p["extra_args"] or "[]")
    if a.seed is not None or a.new_seed:
        out, skip = [], False
        for t in extra:
            if skip: skip = False; continue
            if t == "--seed": skip = True; continue
            out.append(t)
        extra = out
    ns = argparse.Namespace(model=a.model or p["model"],
                            prompt_file=str(pd / "prompt.txt"), config_file=str(cfg),
                            config_json=a.config_json, host=a.host, name=a.name,
                            parent=p["id"], seed=a.seed, new_seed=a.new_seed,
                            ext=a.ext, backend=a.backend or p["backend"],
                            chain=p["chain"], batch=a.batch or p["batch"],
                            upload=[],
                            extra_arg=[" ".join([t]) for t in extra])
    for k, _ in FLAGMAP: setattr(ns, k, None)
    for x in json.loads(p["assets"] or "[]"):
        fpath = pd / x["file"]
        if not fpath.exists(): continue
        flg = x.get("flag")
        matched = False
        if flg:
            for attr, f in FLAGMAP:
                if f == flg:
                    setattr(ns, attr, str(fpath))
                    matched = True
                    break
        if not matched:
            ns.upload.append(str(fpath))
    cmd_add(ns)

def cmd_cancel(a):
    con = db(); sync_hosts(con)
    try:
        return _cmd_cancel(con, a)
    finally:
        con.close()

def _cmd_cancel(con, a):
    job = con.execute("SELECT * FROM jobs WHERE id=?", (a.id,)).fetchone()
    if not job: sys.exit("no such job")
    if job["status"] in ("done", "failed", "cancelled"):
        print("already terminal"); return
    if job["status"] == "queued" or not job["host"]:
        set_job(con, a.id, status="cancelled"); print("cancelled (was queued)"); return
    if (job["backend"] or "oneshot") == "serve":
        set_job(con, a.id, status="cancelling",
                note="serve: no per-job kill — request runs to completion; "
                     "result will be discarded")
        print("marked cancelling (serve backend)"); return
    set_job(con, a.id, status="cancelling")
    qrd = shlex.quote(job["remote_dir"])
    ssh(job["host"], f'pkill -TERM -P "$(cat {qrd}/cli_pid 2>/dev/null)" 2>/dev/null; '
                     f'kill "$(cat {qrd}/cli_pid 2>/dev/null)" 2>/dev/null; '
                     f'kill "$(cat {qrd}/pid 2>/dev/null)" 2>/dev/null; true')
    print("cancel requested — poll will mark it cancelled")

def engine_lock():
    """Non-blocking single-engine guard; returns fd to keep open or None."""
    import fcntl
    fd = open(HERE / "engine.lock", "w")
    try:
        fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
        fd.write(str(os.getpid())); fd.flush()
        return fd
    except OSError:
        fd.close(); return None

def cmd_run(a):
    c, con = conf(), db(); sync_hosts(con)
    lock = engine_lock()
    if not lock:
        sys.exit("another engine is running (ui or run) — see engine.lock holder")
    for j in con.execute("SELECT * FROM jobs WHERE status='uploading'"):
        set_job(con, j["id"], status="queued", note="engine restarted; re-upload")
    print(f"ltxq: polling every {c['poll_secs']}s — Ctrl-C to stop (use tmux/nohup)")
    last_gc = 0
    while True:
        try:
            now = time.time()
            if now - last_gc > 600:
                gc.collect()
                clean_tmp()
                rotate_worker_logs(c, con)
                last_gc = now
            for st in ("running", "suspect", "cancelling"):
                for j in con.execute("SELECT * FROM jobs WHERE status=?", (st,)).fetchall():
                    if (j["backend"] or "oneshot") == "serve":
                        poll_serve_job(c, con, j)
                    else:
                        poll_job(c, con, j)
            for j in con.execute("SELECT * FROM jobs WHERE status='collecting'").fetchall():
                collect(c, con, j)
            dispatch(c, con)
        except KeyboardInterrupt:
            sys.exit(0)
        except Exception as e:
            print("loop error:", repr(e))
        time.sleep(c["poll_secs"])

def cmd_ls(a):
    con = db(); sync_hosts(con); now = int(time.time())
    for j in con.execute("SELECT * FROM jobs ORDER BY created_at DESC LIMIT 50"):
        el = (j["finished_at"] or now) - (j["started_at"] or j["created_at"])
        print(f"{j['id']}  {j['status']:<10} {(j['backend'] or '-'):<7} "
              f"{j['host'] or '-':<8} {j['pct']:>3}%  {el // 60:>4}m  "
              f"{j['name'][:40]}  {(j['note'] or '')[:60]}")

def cmd_probe(a):
    con, c = db(), conf(); sync_hosts(con)
    for h in con.execute("SELECT * FROM hosts WHERE enabled=1").fetchall():
        if not a.alias or h["alias"] == a.alias:
            probe(con, c, h["alias"])

def _models_dir(con, c, alias):
    h = con.execute("SELECT * FROM hosts WHERE alias=?", (alias,)).fetchone()
    if not h: sys.exit("unknown host " + alias)
    if not h["models_dir"]:
        probe(con, c, alias)
        h = con.execute("SELECT * FROM hosts WHERE alias=?", (alias,)).fetchone()
        if not h or not h["models_dir"]:
            sys.exit("models dir not found; set models_dir: in hosts.yaml")
    return h

def cmd_models(a):
    con, c = db(), conf(); sync_hosts(con)
    try:
        return _cmd_models(con, c, a)
    finally:
        con.close()

def _cmd_models(con, c, a):
    h = _models_dir(con, c, a.alias)
    dl = "" if a.catalog else "--downloaded-only "
    r = ssh(a.alias, f'{dollar_home(cli_of(c, h))} models list {dl}'
                     f'--offline --models-dir {shlex.quote(h["models_dir"])}', timeout=120)
    if r.returncode != 0:
        print(f"models list failed rc={r.returncode}: {r.stderr[-300:]}"); return
    hdr = MDIR_HDR.search(r.stdout)
    if hdr:
        same = hdr.group(1).strip().rstrip("/").lower() == h["models_dir"].rstrip("/").lower()
        print(f"resolved dir: {hdr.group(1).strip()}  ->  "
              f"{'MATCHES pin' if same else 'MISMATCH vs pin ' + h['models_dir']}")
    now = int(time.time())
    for m in ROW.finditer(r.stdout):
        mid, name, src, dnl, hf = m.groups()
        con.execute("INSERT OR REPLACE INTO registry VALUES(?,?,?,?,?,?,?)",
                    (a.alias, mid, name.strip(), src, dnl == "yes",
                     None if hf in (None, "-") else hf, now))
    con.commit()
    print(r.stdout.strip())

def cmd_stage(a):
    con, c = db(), conf(); sync_hosts(con)
    h = _models_dir(con, c, a.alias)
    dl = "" if a.allow_download else "--offline"
    print(f"ensure {a.model} on {a.alias} ({h['models_dir']})"
          f"{' [DOWNLOADS ALLOWED]' if a.allow_download else ' [offline]'}")
    r = ssh(a.alias, f'{dollar_home(cli_of(c, h))} models ensure '
                     f'--model {shlex.quote(a.model)} {dl} '
                     f'--models-dir {shlex.quote(h["models_dir"])}', timeout=3600)
    print(r.stdout[-2000:])
    if r.returncode != 0:
        sys.exit(f"ensure failed rc={r.returncode}: {r.stderr[-500:]}")

def cmd_check(a):
    con, c = db(), conf(); sync_hosts(con)
    job = con.execute("SELECT * FROM jobs WHERE id=?", (a.id,)).fetchone()
    if not job: sys.exit("no such job")
    alias = a.host or job["host"]
    if not alias: sys.exit("job has no host yet; pass --host")
    h = _models_dir(con, c, alias)
    have = set(ssh(alias, f"ls -1 {shlex.quote(h['models_dir'])} 2>/dev/null").stdout.split())
    obj = json.loads(job["config_text"] or "{}")
    need = [job["model"]] + [l.get("file") for l in obj.get("loras", []) if l.get("file")]
    missing = []
    for f in need:
        if not f.endswith(".ckpt"):
            print("(skip — not a file id) ", f); continue
        ok = f in have
        print(("ok      " if ok else "MISSING ") + f)
        if not ok: missing.append(f)
    sys.exit(1 if missing else 0)

def cmd_doctor(a):
    print("ltxq doctor")
    con, c = db(), conf(); sync_hosts(con)
    ok = True
    def chk(label, cond, detail=""):
        nonlocal ok
        print(f"  [{'ok' if cond else 'FAIL'}] {label}" +
              (f" — {detail}" if detail and not cond else ""))
        ok = ok and cond
    jid = "doctest0" + uuid.uuid4().hex[:4]
    con.execute("INSERT INTO jobs(id,created_at,status,name) VALUES(?,?,?,?)",
                (jid, int(time.time()), "queued", "doctor"))
    con.commit()
    before = con.execute("SELECT COUNT(*) FROM jobs WHERE status='queued'").fetchone()[0]
    set_job(con, jid, pct=1)
    marked = con.execute("SELECT COUNT(*) FROM jobs WHERE status='queued' AND pct=1"
                         ).fetchone()[0]
    con.execute("DELETE FROM jobs WHERE id=?", (jid,)); con.commit()
    chk("set_job updates only its own row", marked == 1,
        f"{marked}/{before} queued rows touched" if marked != 1 else "")
    for h in con.execute("SELECT * FROM hosts WHERE enabled=1").fetchall():
        r = ssh(h["alias"], "echo ping")
        chk(f"{h['alias']}: ssh reachable", r.returncode == 0,
            r.stderr.strip()[:120])
        pr = ssh(h["alias"],
                 'tail -c +1 /dev/null; echo $((3+1))')
        chk(f"{h['alias']}: remote shell arithmetic ok", "4" in pr.stdout,
            "remote login shell may not be bash/zsh-compatible")
        if _worker_alive(h):
            chk(f"{h['alias']}: serve worker running", True)
        else:
            print(f"  [ --] {h['alias']}: serve worker not running (ok unless "
                  "serve jobs queued)")
    try:
        importlib.metadata.version("flask")
        print("  [ok] flask installed")
    except importlib.metadata.PackageNotFoundError:
        print("  [FAIL] flask not installed — `ui` unavailable"); ok = False
    print("doctor:", "PASS" if ok else "FAIL")

def cmd_ui(a):
    sys.path.insert(0, str(HERE))
    import server
    server.run_ui(a)

def cmd_reconcile(a):
    con, c = db(), conf(); sync_hosts(con)
    clean_tmp()
    rotate_worker_logs(c, con)
    known = {r[0] for r in con.execute("SELECT id FROM jobs")}
    for h in con.execute("SELECT * FROM hosts WHERE enabled=1").fetchall():
        if not h["home"]:
            probe(con, c, h["alias"])
            h = con.execute("SELECT * FROM hosts WHERE alias=?", (h["alias"],)).fetchone()
        rd = f"{h['home']}/{c['remote_root']}/jobs"
        unk = [x for x in ssh(h["alias"], f"ls -1 {shlex.quote(rd)} 2>/dev/null").stdout.split()
               if x not in known]
        print(h["alias"], "unknown remote job dirs:", unk or "none")

def cmd_serve_start(a):
    con, c = db(), conf(); sync_hosts(con)
    try:
        return _cmd_serve_start(con, c, a)
    finally:
        con.close()

def _cmd_serve_start(con, c, a):
    h = _models_dir(con, c, a.alias)
    if not h["home"]:
        probe(con, c, a.alias)
        h = con.execute("SELECT * FROM hosts WHERE alias=?", (a.alias,)).fetchone()
    if _worker_alive(h): print(f"{a.alias}: worker already running"); return
    w = wdir(h)
    qw = shlex.quote(w)
    # v1.4.1: plain-pipe stdin instead of PTY wrapper (PTY breaks serve's
    # newline-delimited JSON protocol); rotate worker.log before boot so we
    # only ever scan bytes written by this worker.
    boot = (f"mkdir -p {qw} && cd {qw} || exit 1; mkdir -p reqs; "
            f"[ -p fifo ] || mkfifo fifo; "
            f'kill "$(cat holder.pid 2>/dev/null)" 2>/dev/null; true; '
            f'kill "$(cat worker.pid 2>/dev/null)" 2>/dev/null; true; '
            f"mv worker.log worker.log.prev 2>/dev/null; "
            f"nohup {shlex.quote(dollar_home(cli_of(c, h)).replace('$HOME', h['home'], 1))} serve "
            f"< fifo >> worker.log 2>&1 & echo $! > worker.pid; "
            f"nohup sleep 100000 > fifo 2>/dev/null & echo $! > holder.pid")
    r = ssh(a.alias, boot, timeout=30)
    if r.returncode != 0:
        print(f"{a.alias}: boot script failed rc={r.returncode}: "
              f"{(r.stderr or r.stdout).strip()[:300]}"); return
    base = 0
    out = ""
    for _ in range(15):
        time.sleep(2)
        out = ssh(a.alias,
                  f'cat {qw}/worker.log 2>/dev/null; '
                  f'echo ---POST; kill -0 "$(cat {qw}/worker.pid 2>/dev/null)" '
                  f'2>/dev/null && echo ALIVE || echo DEAD')
        if '"ready"' in out.stdout:
            print(f"{a.alias}: serve worker ready ({w})"); return
    post = out.stdout.split("---POST", 1)[-1].strip()
    if post == "DEAD":
        print(f"{a.alias}: worker died at startup (error should be at top of worker.log)")
    else:
        print(f"{a.alias}: no ready event in 30s (worker process still alive)")
    print(f"— state: worker.pid=$(cat {qw}/worker.pid 2>/dev/null) "
          f"holder.pid=$(cat {qw}/holder.pid 2>/dev/null)")
    t = ssh(a.alias, f"tail -c 800 {qw}/worker.log 2>/dev/null").stdout.strip()
    if t: print(f"— worker.log:\n{t}")

def cmd_serve_stop(a):
    con, c = db(), conf(); sync_hosts(con)
    h = con.execute("SELECT * FROM hosts WHERE alias=?", (a.alias,)).fetchone()
    if not h: sys.exit("unknown host")
    busy = con.execute("SELECT id FROM jobs WHERE host=? AND backend='serve' AND status IN "
                       "('running','uploading','suspect','cancelling')",
                       (a.alias,)).fetchone()
    if busy and not a.force:
        sys.exit(f"serve job {busy[0]} in flight; shutdown mid-job semantics unspecified "
                 f"— --force to proceed")
    ssh(a.alias, f"echo {SHUTDOWN} > {shlex.quote(wdir(h))}/fifo")
    print("shutdown sent (holder dies on next serve-start); verify via worker.log")

def main():
    p = argparse.ArgumentParser(prog="ltxq")
    sp = p.add_subparsers(dest="cmd", required=True)
    g = sp.add_parser("add"); g.add_argument("--model", required=True)
    g.add_argument("--prompt-file", required=True); g.add_argument("--config-file")
    g.add_argument("--config-json"); g.add_argument("--host")
    g.add_argument("--name"); g.add_argument("--parent", help=argparse.SUPPRESS)
    g.add_argument("--seed", type=int); g.add_argument("--new-seed", action="store_true")
    g.add_argument("--ext", default="mov", choices=["mov", "mp4", "png"])
    g.add_argument("--backend", choices=["oneshot", "serve"])
    for f in ("--image", "--audio", "--first-frame", "--middle-frame",
              "--last-frame", "--input-video"):
        g.add_argument(f)
    g.add_argument("--upload", action="append", default=[])
    g.add_argument("--extra-arg", action="append", default=[],
                   help='raw tokens, e.g. --extra-arg "--keyframe kf.png:12:0.8"')
    g.add_argument("--chain", choices=["first_frame", "image"],
                   help="continue from the previous generation: at launch time, "
                        "attach the last frame of the newest finished render "
                        "to this slot")
    g.add_argument("--batch", help="group label (e.g. moodboard-v1); 'chain' then "
                                   "scopes to the previous finished job in this batch")
    g = sp.add_parser("regen"); g.add_argument("id")
    g.add_argument("--model"); g.add_argument("--config-json"); g.add_argument("--host")
    g.add_argument("--name"); g.add_argument("--seed", type=int)
    g.add_argument("--new-seed", action="store_true")
    g.add_argument("--ext", default="mov", choices=["mov", "mp4", "png"])
    g.add_argument("--backend", choices=["oneshot", "serve"])
    g.add_argument("--batch", help="override the group label (default: keep the original)")
    sp.add_parser("ls"); sp.add_parser("run"); sp.add_parser("reconcile")
    sp.add_parser("doctor")
    g = sp.add_parser("ui"); g.add_argument("--port", type=int, default=8765)
    g.add_argument("--no-engine", action="store_true",
                   help="serve UI without the run loop (external `run` in tmux)")
    g = sp.add_parser("probe"); g.add_argument("alias", nargs="?")
    g = sp.add_parser("models"); g.add_argument("alias"); g.add_argument("--catalog",
                                                                        action="store_true")
    g = sp.add_parser("stage"); g.add_argument("alias"); g.add_argument("model")
    g.add_argument("--allow-download", action="store_true")
    g = sp.add_parser("check"); g.add_argument("id"); g.add_argument("--host")
    g = sp.add_parser("cancel"); g.add_argument("id")
    g = sp.add_parser("serve-start"); g.add_argument("alias")
    g = sp.add_parser("serve-stop"); g.add_argument("alias")
    g.add_argument("--force", action="store_true")
    args = p.parse_args()
    {"add": cmd_add, "ls": cmd_ls, "run": cmd_run, "cancel": cmd_cancel,
     "regen": cmd_regen, "probe": cmd_probe, "reconcile": cmd_reconcile,
     "models": cmd_models, "check": cmd_check, "stage": cmd_stage,
     "serve-start": cmd_serve_start, "serve-stop": cmd_serve_stop,
     "doctor": cmd_doctor, "ui": cmd_ui}[args.cmd](args)

if __name__ == "__main__":
    main()
